# Generated by Django 4.2.7 on 2024-02-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=25)),
                ('selling_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='uploads/to')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp3.category')),
            ],
        ),
    ]
