# Generated by Django 4.2.7 on 2024-02-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp3', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
